spring.application.name=COLLEGE-MANAGEMENT

# Server port (optional)
server.port=8080

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/college_db
spring.datasource.username=college_user
spring.datasource.password=ZBCDFGHJKLqw821

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
